fieldLayouts:
  57882591-84f8-4e81-a79c-b2a8a2992f55:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3ccd4970-5d0f-4be3-9752-85b382ea914e
            userCondition: null
            warning: null
            width: 100
          -
            dismissible: false
            elementCondition: null
            style: warning
            tip: 'The custom fields that are added are nowhere to be found!'
            type: craft\fieldlayoutelements\Tip
            uid: 77164c58-9792-4eb0-98fa-bbfd7e0802c1
            userCondition: null
          -
            elementCondition: null
            fieldUid: 9b5a1fd9-dbf5-4d8a-9709-e53cba5e1ab4 # Hyper Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b5e878b-de1e-4b90-a0d9-a59ec62fa119
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d7a904de-bb54-4076-bd39-98ccb619636d
        userCondition: null
handle: hyper
hasTitleField: true
name: Hyper
section: 86b465e9-8352-447c-852d-5dc36e6b2efb # Hyper
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
